version: '3.8'

services:

  # Backend API
  face-finder-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/face-finder-api
    environment:
      POSTGRES_URI: postgres://user:secret@postgres:5432/face-finder-docker
    links:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/face-finder-api

  # Postgres
  postgres:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: face-finder-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"